[package]
name = "eckert"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.28.0"
voronoice = "0.2.0"
wkt = "0.10.3"
